enum NVME_FIRMWARE_ACTIVATE_ACTIONS
{
    NVME_FIRMWARE_ACTIVATE_ACTION_DOWNLOAD_TO_SLOT=0,
    NVME_FIRMWARE_ACTIVATE_ACTION_DOWNLOAD_TO_SLOT_AND_ACTIVATE=1,
    NVME_FIRMWARE_ACTIVATE_ACTION_ACTIVATE=2,
    NVME_FIRMWARE_ACTIVATE_ACTION_DOWNLOAD_TO_SLOT_AND_ACTIVATE_IMMEDIATE=3
};
