enum NVME_SANITIZE_ACTION
{
    NVME_SANITIZE_ACTION_RESERVED=0,
    NVME_SANITIZE_ACTION_EXIT_FAILURE_MODE=1,
    NVME_SANITIZE_ACTION_START_BLOCK_ERASE_SANITIZE=2,
    NVME_SANITIZE_ACTION_START_OVERWRITE_SANITIZE=3,
    NVME_SANITIZE_ACTION_START_CRYPTO_ERASE_SANITIZE=4
};
