enum NVME_STATUS_MEDIA_ERROR_CODES
{
    NVME_STATUS_NVM_WRITE_FAULT=128,
    NVME_STATUS_NVM_UNRECOVERED_READ_ERROR=129,
    NVME_STATUS_NVM_END_TO_END_GUARD_CHECK_ERROR=130,
    NVME_STATUS_NVM_END_TO_END_APPLICATION_TAG_CHECK_ERROR=131,
    NVME_STATUS_NVM_END_TO_END_REFERENCE_TAG_CHECK_ERROR=132,
    NVME_STATUS_NVM_COMPARE_FAILURE=133,
    NVME_STATUS_NVM_ACCESS_DENIED=134,
    NVME_STATUS_NVM_DEALLOCATED_OR_UNWRITTEN_LOGICAL_BLOCK=135
};
