enum NVME_PROTECTION_INFORMATION_TYPES
{
    NVME_PROTECTION_INFORMATION_NOT_ENABLED=0,
    NVME_PROTECTION_INFORMATION_TYPE1=1,
    NVME_PROTECTION_INFORMATION_TYPE2=2,
    NVME_PROTECTION_INFORMATION_TYPE3=3
};
