enum _D3DKMDT_MONITOR_DESCRIPTOR_TYPE
{
    D3DKMDT_MDT_UNINITIALIZED=0,
    D3DKMDT_MDT_VESA_EDID_V1_BASEBLOCK=1,
    D3DKMDT_MDT_VESA_EDID_V1_BLOCKMAP=2,
    D3DKMDT_MDT_OTHER=255
};

enum _D3DKMDT_MONITOR_CAPABILITIES_ORIGIN
{
    D3DKMDT_MCO_UNINITIALIZED=0,
    D3DKMDT_MCO_DEFAULTMONITORPROFILE=1,
    D3DKMDT_MCO_MONITORDESCRIPTOR=2,
    D3DKMDT_MCO_MONITORDESCRIPTOR_REGISTRYOVERRIDE=3,
    D3DKMDT_MCO_SPECIFICCAP_REGISTRYOVERRIDE=4,
    D3DKMDT_MCO_DRIVER=5
};

struct _DMM_MONITORDESCRIPTOR_SERIALIZATION// Size=0x8c (Id=218)
{
    unsigned int Id;// Offset=0x0 Size=0x4
    enum _D3DKMDT_MONITOR_DESCRIPTOR_TYPE Type;// Offset=0x4 Size=0x4
    enum _D3DKMDT_MONITOR_CAPABILITIES_ORIGIN Origin;// Offset=0x8 Size=0x4
    unsigned char Data[128];// Offset=0xc Size=0x80
};
