struct _CONTROLLER_COUNTER// Size=0x100 (Id=491)
{
    unsigned char NeedsReporting;// Offset=0x0 Size=0x1
    unsigned long ResetCount;// Offset=0x4 Size=0x4
    unsigned long RestoreStateFailureCount;// Offset=0x8 Size=0x4
    unsigned long RestoreFailedHaltedNotSetCount;// Offset=0xc Size=0x4
    unsigned long RestoreFailedSaveStateStatusSetCount;// Offset=0x10 Size=0x4
    unsigned long RestoreFailedRestoreStateStatusSetCount;// Offset=0x14 Size=0x4
    unsigned long RestoreFailedSaveRestoreErrorSetCount;// Offset=0x18 Size=0x4
    unsigned long RestoreFailedRelaxedTimeoutCount;// Offset=0x1c Size=0x4
    unsigned long RestoreFailedRelaxedTimeoutByMSCount;// Offset=0x20 Size=0x4
    unsigned long RestoreFailedDefaultTimeoutCount;// Offset=0x24 Size=0x4
    unsigned long RHResumeTimeoutCount;// Offset=0x28 Size=0x4
    unsigned long RHResumeNeededExtendedWaitCount;// Offset=0x2c Size=0x4
    unsigned long RHSuspendTimeoutCount;// Offset=0x30 Size=0x4
    unsigned long RHSuspendNeededExtendedWaitCount;// Offset=0x34 Size=0x4
    unsigned long RHPLCClearedOnU0PriorToU3Count;// Offset=0x38 Size=0x4
    unsigned long ContextStateErrorCount;// Offset=0x3c Size=0x4
    unsigned long StopEndpointSuccessRetryMaxCount;// Offset=0x40 Size=0x4
    unsigned long StopEndpointFailureAfterRetriesCount;// Offset=0x44 Size=0x4
    unsigned long SplitTransactionErrorsCount;// Offset=0x48 Size=0x4
    unsigned long StopEndpointRetryInNotStoppedStateSuccessCount;// Offset=0x4c Size=0x4
    unsigned long StopEndpointRetryInNotStoppedStateFailureCount;// Offset=0x50 Size=0x4
    unsigned long SetDequeuePointerRetrySuccessCount;// Offset=0x54 Size=0x4
    unsigned long SetDequeuePointerRetryFailureCount;// Offset=0x58 Size=0x4
    unsigned long StaleEventsWithEventDataSetDroppedCount;// Offset=0x5c Size=0x4
    unsigned long UpgradeIgnoreContextErrorOnEPStopAsDefaultBehaviorSuccessCount;// Offset=0x60 Size=0x4
    unsigned long UpgradeIgnoreContextErrorOnEPStopAsDefaultBehaviorFailureCount;// Offset=0x64 Size=0x4
    unsigned long RelaxedTimeoutForRegisterStopSuccessCount;// Offset=0x68 Size=0x4
    unsigned long RelaxedTimeoutForRegisterStopFailureCount;// Offset=0x6c Size=0x4
    unsigned long RelaxedTimeoutForControllerRestoreSuccessCount;// Offset=0x70 Size=0x4
    unsigned long RelaxedTimeoutForControllerRestoreFailureCount;// Offset=0x74 Size=0x4
    unsigned long StopEndpointRetryInNotStoppedStateSuccessMaxRetries;// Offset=0x78 Size=0x4
    unsigned long SetDequeuePointerRetrySuccessMaxRetries;// Offset=0x7c Size=0x4
    unsigned long RelaxedTimeoutForRegisterStopSuccessMaxRetries;// Offset=0x80 Size=0x4
    unsigned long RelaxedTimeoutForControllerRestoreSuccessMaxRetries;// Offset=0x84 Size=0x4
    unsigned long ResetCountTotal;// Offset=0x88 Size=0x4
    unsigned long RestoreStateFailureCountTotal;// Offset=0x8c Size=0x4
    unsigned long RestoreFailedHaltedNotSetCountTotal;// Offset=0x90 Size=0x4
    unsigned long RestoreFailedSaveStateStatusSetCountTotal;// Offset=0x94 Size=0x4
    unsigned long RestoreFailedRestoreStateStatusSetCountTotal;// Offset=0x98 Size=0x4
    unsigned long RestoreFailedSaveRestoreErrorSetCountTotal;// Offset=0x9c Size=0x4
    unsigned long RestoreFailedRelaxedTimeoutCountTotal;// Offset=0xa0 Size=0x4
    unsigned long RestoreFailedRelaxedTimeoutByMSCountTotal;// Offset=0xa4 Size=0x4
    unsigned long RestoreFailedDefaultTimeoutCountTotal;// Offset=0xa8 Size=0x4
    unsigned long RHResumeTimeoutCountTotal;// Offset=0xac Size=0x4
    unsigned long RHResumeNeededExtendedWaitCountTotal;// Offset=0xb0 Size=0x4
    unsigned long RHSuspendTimeoutCountTotal;// Offset=0xb4 Size=0x4
    unsigned long RHSuspendNeededExtendedWaitCountTotal;// Offset=0xb8 Size=0x4
    unsigned long RHPLCClearedOnU0PriorToU3CountTotal;// Offset=0xbc Size=0x4
    unsigned long ContextStateErrorCountTotal;// Offset=0xc0 Size=0x4
    unsigned long StopEndpointSuccessRetryMaxCountTotal;// Offset=0xc4 Size=0x4
    unsigned long StopEndpointFailureAfterRetriesCountTotal;// Offset=0xc8 Size=0x4
    unsigned long StopEndpointRetryInNotStoppedStateSuccessCountTotal;// Offset=0xcc Size=0x4
    unsigned long StopEndpointRetryInNotStoppedStateFailureCountTotal;// Offset=0xd0 Size=0x4
    unsigned long SetDequeuePointerRetrySuccessCountTotal;// Offset=0xd4 Size=0x4
    unsigned long SetDequeuePointerRetryFailureCountTotal;// Offset=0xd8 Size=0x4
    unsigned long StaleEventsWithEventDataSetDroppedCountTotal;// Offset=0xdc Size=0x4
    unsigned long UpgradeIgnoreContextErrorOnEPStopAsDefaultBehaviorSuccessCountTotal;// Offset=0xe0 Size=0x4
    unsigned long UpgradeIgnoreContextErrorOnEPStopAsDefaultBehaviorFailureCountTotal;// Offset=0xe4 Size=0x4
    unsigned long RelaxedTimeoutForRegisterStopSuccessCountTotal;// Offset=0xe8 Size=0x4
    unsigned long RelaxedTimeoutForRegisterStopFailureCountTotal;// Offset=0xec Size=0x4
    unsigned long RelaxedTimeoutForControllerRestoreSuccessCountTotal;// Offset=0xf0 Size=0x4
    unsigned long RelaxedTimeoutForControllerRestoreFailureCountTotal;// Offset=0xf4 Size=0x4
    unsigned long SplitTransactionErrorsCountTotal;// Offset=0xf8 Size=0x4
    unsigned long HealthCheckEventCountTotal;// Offset=0xfc Size=0x4
};
