enum MFND_CHILD_CONTROLLER_CONTROL_SELECT
{
    MFND_CHILD_CONTROLLER_CONTROL_SELECT_SECURE_ERASE=0,
    MFND_CHILD_CONTROLLER_CONTROL_SELECT_PAUSE=1,
    MFND_CHILD_CONTROLLER_CONTROL_SELECT_RESUME=2,
    MFND_CHILD_CONTROLLER_CONTROL_SELECT_SHUTDOWN=3
};
