enum MFND_NAMESPACE_PAGE_MAP_OPERATION_SELECT
{
    MFND_NAMESPACE_PAGE_MAP_OPERATION_SELECT_START_CHANGE_TRACKING=0,
    MFND_NAMESPACE_PAGE_MAP_OPERATION_SELECT_STOP_CHANGE_TRACKING=1,
    MFND_NAMESPACE_PAGE_MAP_OPERATION_SELECT_SWAP_NAMESPACE_DIRTY_PAGES=2
};
