enum _SSH_ENABLE_STATUS
{
    SSH_ENABLED_BY_DEFAULT=1,
    SSH_ENABLED_VIA_POWER_POLICY=2,
    SSH_DISABLED_VIA_POWER_POLICY=3,
    SSH_ENABLED_VIA_WMI=4,
    SSH_DISABLED_VIA_WMI=5,
    SSH_DISABLED_VIA_USBPORT=6
};
