enum _DMM_VIDPN_MONITOR_TYPE
{
    DMM_VMT_UNINITIALIZED=0,
    DMM_VMT_PHYSICAL_MONITOR=1,
    DMM_VMT_BOOT_PERSISTENT_MONITOR=2,
    DMM_VMT_PERSISTENT_MONITOR=3,
    DMM_VMT_TEMPORARY_MONITOR=4,
    DMM_VMT_SIMULATED_MONITOR=5
};
