enum _NDIS_LWFDRV_REFTAG
{
    LWFDRV_ATTACHING=0,
    LWFDRV_IOWORKITEM=1,
    LWFDRV_IOWORKITEMC=2,
    LWFDRV_FILTERMODULE=3,
    LWFDRV_PD_CLIENT=4,
    LWFDRV_RUNDOWN=5,
    LWFDRV_NUMBER_OF_TAGS=6
};
