struct _WDFSTRUCTURES// Size=0x288 (Id=2343)
{
    unsigned long long SIZE_WDF_CHILD_ADDRESS_DESCRIPTION_HEADER;// Offset=0x0 Size=0x8
    unsigned long long SIZE_WDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER;// Offset=0x8 Size=0x8
    unsigned long long SIZE_WDF_CHILD_LIST_CONFIG;// Offset=0x10 Size=0x8
    unsigned long long SIZE_WDF_CHILD_LIST_ITERATOR;// Offset=0x18 Size=0x8
    unsigned long long SIZE_WDF_CHILD_RETRIEVE_INFO;// Offset=0x20 Size=0x8
    unsigned long long SIZE_WDF_CLASS_BIND_INFO;// Offset=0x28 Size=0x8
    unsigned long long SIZE_WDF_CLASS_BIND_INFO2;// Offset=0x30 Size=0x8
    unsigned long long SIZE_WDF_CLASS_EXTENSION_DESCRIPTOR;// Offset=0x38 Size=0x8
    unsigned long long SIZE_WDF_CLASS_LIBRARY_INFO;// Offset=0x40 Size=0x8
    unsigned long long SIZE_WDF_CLASS_VERSION;// Offset=0x48 Size=0x8
    unsigned long long SIZE_WDF_COMMON_BUFFER_CONFIG;// Offset=0x50 Size=0x8
    unsigned long long SIZE_WDF_CUSTOM_TYPE_CONTEXT;// Offset=0x58 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_PNP_CAPABILITIES;// Offset=0x60 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_PNP_NOTIFICATION_DATA;// Offset=0x68 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_POWER_CAPABILITIES;// Offset=0x70 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_POWER_NOTIFICATION_DATA;// Offset=0x78 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_POWER_POLICY_IDLE_SETTINGS;// Offset=0x80 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_POWER_POLICY_NOTIFICATION_DATA;// Offset=0x88 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_POWER_POLICY_WAKE_SETTINGS;// Offset=0x90 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_PROPERTY_DATA;// Offset=0x98 Size=0x8
    unsigned long long SIZE_WDF_DEVICE_STATE;// Offset=0xa0 Size=0x8
    unsigned long long SIZE_WDF_DMA_ENABLER_CONFIG;// Offset=0xa8 Size=0x8
    unsigned long long SIZE_WDF_DMA_SYSTEM_PROFILE_CONFIG;// Offset=0xb0 Size=0x8
    unsigned long long SIZE_WDF_DPC_CONFIG;// Offset=0xb8 Size=0x8
    unsigned long long SIZE_WDF_DRIVER_CONFIG;// Offset=0xc0 Size=0x8
    unsigned long long SIZE_WDF_DRIVER_GLOBALS;// Offset=0xc8 Size=0x8
    unsigned long long SIZE_WDF_DRIVER_VERSION_AVAILABLE_PARAMS;// Offset=0xd0 Size=0x8
    unsigned long long SIZE_WDF_FDO_EVENT_CALLBACKS;// Offset=0xd8 Size=0x8
    unsigned long long SIZE_WDF_FILEOBJECT_CONFIG;// Offset=0xe0 Size=0x8
    unsigned long long SIZE_WDF_INTERRUPT_CONFIG;// Offset=0xe8 Size=0x8
    unsigned long long SIZE_WDF_INTERRUPT_EXTENDED_POLICY;// Offset=0xf0 Size=0x8
    unsigned long long SIZE_WDF_INTERRUPT_INFO;// Offset=0xf8 Size=0x8
    unsigned long long SIZE_WDF_IO_FORWARD_PROGRESS_RESERVED_POLICY_SETTINGS;// Offset=0x100 Size=0x8
    unsigned long long SIZE_WDF_IO_QUEUE_CONFIG;// Offset=0x108 Size=0x8
    unsigned long long SIZE_WDF_IO_QUEUE_FORWARD_PROGRESS_POLICY;// Offset=0x110 Size=0x8
    unsigned long long SIZE_WDF_IO_TARGET_OPEN_PARAMS;// Offset=0x118 Size=0x8
    unsigned long long SIZE_WDF_IO_TYPE_CONFIG;// Offset=0x120 Size=0x8
    unsigned long long SIZE_WDF_MEMORY_DESCRIPTOR;// Offset=0x128 Size=0x8
    unsigned long long SIZE_WDF_OBJECT_ATTRIBUTES;// Offset=0x130 Size=0x8
    unsigned long long SIZE_WDF_OBJECT_CONTEXT_TYPE_INFO;// Offset=0x138 Size=0x8
    unsigned long long SIZE_WDF_PDO_EVENT_CALLBACKS;// Offset=0x140 Size=0x8
    unsigned long long SIZE_WDF_PNPPOWER_EVENT_CALLBACKS;// Offset=0x148 Size=0x8
    unsigned long long SIZE_WDF_POWER_FRAMEWORK_SETTINGS;// Offset=0x150 Size=0x8
    unsigned long long SIZE_WDF_POWER_POLICY_EVENT_CALLBACKS;// Offset=0x158 Size=0x8
    unsigned long long SIZE_WDF_POWER_ROUTINE_TIMED_OUT_DATA;// Offset=0x160 Size=0x8
    unsigned long long SIZE_WDF_QUERY_INTERFACE_CONFIG;// Offset=0x168 Size=0x8
    unsigned long long SIZE_WDF_QUEUE_FATAL_ERROR_DATA;// Offset=0x170 Size=0x8
    unsigned long long SIZE_WDF_REMOVE_LOCK_OPTIONS;// Offset=0x178 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_COMPLETION_PARAMS;// Offset=0x180 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_FATAL_ERROR_INFORMATION_LENGTH_MISMATCH_DATA;// Offset=0x188 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_FORWARD_OPTIONS;// Offset=0x190 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_PARAMETERS;// Offset=0x198 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_REUSE_PARAMS;// Offset=0x1a0 Size=0x8
    unsigned long long SIZE_WDF_REQUEST_SEND_OPTIONS;// Offset=0x1a8 Size=0x8
    unsigned long long SIZE_WDF_TASK_SEND_OPTIONS;// Offset=0x1b0 Size=0x8
    unsigned long long SIZE_WDF_TIMER_CONFIG;// Offset=0x1b8 Size=0x8
    unsigned long long SIZE_WDF_TRIAGE_INFO;// Offset=0x1c0 Size=0x8
    unsigned long long SIZE_WDF_USB_CONTINUOUS_READER_CONFIG;// Offset=0x1c8 Size=0x8
    unsigned long long SIZE_WDF_USB_DEVICE_CREATE_CONFIG;// Offset=0x1d0 Size=0x8
    unsigned long long SIZE_WDF_USB_DEVICE_INFORMATION;// Offset=0x1d8 Size=0x8
    unsigned long long SIZE_WDF_USB_DEVICE_SELECT_CONFIG_PARAMS;// Offset=0x1e0 Size=0x8
    unsigned long long SIZE_WDF_USB_INTERFACE_SELECT_SETTING_PARAMS;// Offset=0x1e8 Size=0x8
    unsigned long long SIZE_WDF_USB_INTERFACE_SETTING_PAIR;// Offset=0x1f0 Size=0x8
    unsigned long long SIZE_WDF_USB_PIPE_INFORMATION;// Offset=0x1f8 Size=0x8
    unsigned long long SIZE_WDF_USB_REQUEST_COMPLETION_PARAMS;// Offset=0x200 Size=0x8
    unsigned long long SIZE_WDF_WMI_INSTANCE_CONFIG;// Offset=0x208 Size=0x8
    unsigned long long SIZE_WDF_WMI_PROVIDER_CONFIG;// Offset=0x210 Size=0x8
    unsigned long long SIZE_WDF_WORKITEM_CONFIG;// Offset=0x218 Size=0x8
    unsigned long long SIZE_WDFCONTEXT_TRIAGE_INFO;// Offset=0x220 Size=0x8
    unsigned long long SIZE_WDFCONTEXTTYPE_TRIAGE_INFO;// Offset=0x228 Size=0x8
    unsigned long long SIZE_WDFCX_FILEOBJECT_CONFIG;// Offset=0x230 Size=0x8
    unsigned long long SIZE_WDFCX_PNPPOWER_EVENT_CALLBACKS;// Offset=0x238 Size=0x8
    unsigned long long SIZE_WDFDEVICE_TRIAGE_INFO;// Offset=0x240 Size=0x8
    unsigned long long SIZE_WDFFWDPROGRESS_TRIAGE_INFO;// Offset=0x248 Size=0x8
    unsigned long long SIZE_WDFIRP_TRIAGE_INFO;// Offset=0x250 Size=0x8
    unsigned long long SIZE_WDFIRPQUEUE_TRIAGE_INFO;// Offset=0x258 Size=0x8
    unsigned long long SIZE_WDFMEMORY_OFFSET;// Offset=0x260 Size=0x8
    unsigned long long SIZE_WDFOBJECT_TRIAGE_INFO;// Offset=0x268 Size=0x8
    unsigned long long SIZE_WDFQUEUE_TRIAGE_INFO;// Offset=0x270 Size=0x8
    unsigned long long SIZE_WDFREQUEST_TRIAGE_INFO;// Offset=0x278 Size=0x8
    unsigned long long SIZE_WDFCX_POWER_POLICY_EVENT_CALLBACKS;// Offset=0x280 Size=0x8
};
