enum _D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL
{
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_NO_CHANGE=0,
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_ENABLE=1,
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_BYPASS=2
};
