enum FXOBJECT_FLAGS
{
    FXOBJECT_FLAGS_PASSIVE_CALLBACKS=1,
    FXOBJECT_FLAGS_NODELETEDDI=2,
    FXOBJECT_FLAGS_DELETECALLED=4,
    FXOBJECT_FLAGS_COMMITTED=8,
    FXOBJECT_FLAGS_PASSIVE_DISPOSE=16,
    FXOBJECT_FLAGS_FORCE_DISPOSE_THREAD=32,
    FXOBJECT_FLAGS_HAS_DEBUG=128,
    FXOBJECT_FLAGS_EARLY_DISPOSED_EXT=256,
    FXOBJECT_FLAGS_TRACE_STATE=512,
    FXOBJECT_FLAGS_HAS_CLEANUP=1024,
    FXOBJECT_FLAGS_DISPOSE_OVERRIDE=2048
};
