enum FxRequestVerifierFlags
{
    FXREQUEST_FLAG_DRIVER_OWNED=1,
    FXREQUEST_FLAG_TAG_REQUEST=2,
    FXREQUEST_FLAG_FORWARDED=4,
    FXREQUEST_FLAG_DRIVER_DISPATCH=8,
    FXREQUEST_FLAG_DRIVER_CANCELABLE=16,
    FXREQUEST_FLAG_DRIVER_INPROCESS_CONTEXT=32,
    FXREQUEST_FLAG_CANCELLED=64,
    FXREQUEST_FLAG_FORMATTED=128,
    FXREQUEST_FLAG_SENT_TO_TARGET=256,
    FXREQUEST_FLAG_DRIVER_IN_EVTIOSTOP_CONTEXT=512,
    FXREQUEST_FLAG_RESERVED_REQUEST_ASSOCIATED_WITH_IRP=1024
};
