enum _FSCTL_REFS_VOLUME_ATTESTATION_ATTESTED_STATE
{
    FSCTL_REFS_VOLUME_ATTESTATION_ATTESTED_IS_ATTESTED=1,
    FSCTL_REFS_VOLUME_ATTESTATION_ATTESTED_WITH_CERTIFICATE=2,
    FSCTL_REFS_VOLUME_ATTESTATION_ATTESTED_WITH_TPM=4
};
