enum _UCX_ENDPOINT_CHARACTERISTIC_TYPE
{
    UCX_ENDPOINT_CHARACTERISTIC_TYPE_PRIORITY=1
};

enum _UCX_ENDPOINT_CHARACTERISTIC_PRIORITY
{
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_NONE=0,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_VIDEO=1,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_VOICE=2,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_INTERACTIVE=3
};

struct _UCX_ENDPOINT_CHARACTERISTIC// Size=0xc (Id=764)
{
    unsigned long Size;// Offset=0x0 Size=0x4
    enum _UCX_ENDPOINT_CHARACTERISTIC_TYPE CharacteristicType;// Offset=0x4 Size=0x4
    enum _UCX_ENDPOINT_CHARACTERISTIC_PRIORITY Priority;// Offset=0x8 Size=0x4
};
