enum _UCX_ENDPOINT_CHARACTERISTIC_PRIORITY
{
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_NONE=0,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_VIDEO=1,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_VOICE=2,
    UCX_ENDPOINT_CHARACTERISTIC_PRIORITY_BULK_INTERACTIVE=3
};
