enum _GENERIC_STATE
{
    GenericStateIgnored=1000,
    GenericStateEmptySubState=1001,
    GenericStateNull=1002
};

enum _ESM_STATE
{
    EsmStateIgnored=1000,
    EsmStateEmptySubState=1001,
    EsmStateNull=1002,
    EsmStateCompleteWithStatusFailed=1003,
    EsmStateRequestPortCycle=1004,
    EsmStateSignalQueryDeviceTextEvent=1005,
    EsmStateCompleteFDORequestWithStatusFailed=1006,
    EsmStateCompleteGetPortStatusWithInternalError=1007,
    EsmStateCompleteGetPortStatusWithNoSuchDevice=1008,
    EsmStateDisabled=2000,
    EsmStateAcknowledgingControllerResetComplete=2001,
    EsmStateAcknowledgingControllerResetCompleteInDisabled=2002,
    EsmStateCheckingIfControllerHasKnownIssuesInDeliveringFSE=2003,
    EsmStateCheckingIfEndpointCanBeResetAfterHalt=2004,
    EsmStateCheckingIfEndpointShouldBeAutoReset=2005,
    EsmStateCheckingIfEndpointShouldBeReconfiguredAfterStop=2006,
    EsmStateCheckingIfEndpointShouldBeReconfiguredOnResetWhenNotHalted=2007,
    EsmStateCheckingIfEndpointShouldBeStopped=2008,
    EsmStateCheckingIfIgnoreContextErrorOnEPStopFlagIsSet=2009,
    EsmStateCheckingIfStopEndpointCommandShouldBeDelayed=2010,
    EsmStateCheckingIfStopEndpontReissueCountReached=2011,
    EsmStateCompletingClientResetRequest=2012,
    EsmStateCompletingClientResetRequestAfterEndpointReconfigure=2013,
    EsmStateCompletingClientResetRequestAfterEndpointReconfigureFailure=2014,
    EsmStateCompletingClientResetRequestAfterResetFailure=2015,
    EsmStateCompletingClientResetRequestDueToOutstandingTransfers=2016,
    EsmStateCompletingResetRequestWhenEndpointNotHalted=2017,
    EsmStateDroppingFSEAfterStop=2018,
    EsmStateEnabledAndMapping=2019,
    EsmStateNotifyingTransferRingsEndpointHalted=2020,
    EsmStateNotifyingTransferRingsEndpointResetFromClient=2021,
    EsmStateNotifyingTransferRingsFSEReceived=2022,
    EsmStateNotifyingTransferRingsOkToReclaimTransfersOnCancel=2023,
    EsmStateNotifyingUCXAboutTransferCancellation=2024,
    EsmStateProcessingExpectedEventTRBsAfterEndpointHalt=2025,
    EsmStateProcessingExpectedEventTRBsAfterEndpointStop=2026,
    EsmStatePurgingTransferRingQueuesIfNeeded=2027,
    EsmStateReclaimingCanceledTransfersAfterControllerSurpriseRemoval=2028,
    EsmStateReclaimingTransfersAfterControlEndpointAutoReset=2029,
    EsmStateReclaimingTransfersAfterControllerReset=2030,
    EsmStateReclaimingTransfersAfterEndpointStop=2031,
    EsmStateReconfiguringEndpointAfterStop=2032,
    EsmStateReconfiguringEndpointOnReset=2033,
    EsmStateRequeuingPendingTransfersAfterHaltClear=2034,
    EsmStateResettingControlEndpoint=2035,
    EsmStateResettingControllerDueToRepeatedStopEndpointFailure=2036,
    EsmStateResettingEndpoint=2037,
    EsmStateRestartingTransferRingQueuesIfNeeded=2038,
    EsmStateSimulatingEndpointHaltReceivedOnTimeout=2039,
    EsmStateSimulatingExpectedEventTRBsProcessedAfterHaltOnTimeout=2040,
    EsmStateSimulatingExpectedEventTRBsProcessedOnTimeout=2041,
    EsmStateSimulatingFSEReceivedOnTimeout=2042,
    EsmStateStartingMapping=2043,
    EsmStateStoppingEndpoint=2044,
    EsmStateStoppingMappingAfterControllerResetInEnabled=2045,
    EsmStateStoppingMappingAfterControllerSurpriseRemovalInEnabled=2046,
    EsmStateStoppingMappingBeforeEndpointReconfigure=2047,
    EsmStateStoppingMappingOnCancelStart=2048,
    EsmStateStoppingMappingOnHalt=2049,
    EsmStateUpdatingTransferRingDequeuePointers=2050,
    EsmStateWaitingForControllerResetCompletion=2051,
    EsmStateWaitingForControllerResetCompletionInEnabled=2052,
    EsmStateWaitingForControllerResetOrSurpriseRemovalNotification=2053,
    EsmStateWaitingForEndpointDisable=2054,
    EsmStateWaitingForFSEAfterStopEndpointCommandCompletion=2055,
    EsmStateWaitingForHaltedCompletionCode=2056,
    EsmStateWaitingForResetRequestFromClient=2057,
    EsmStateWaitingToReissueStopEndpointCommand1=2058,
    EsmStateWaitingToReissueStopEndpointCommand2=2059
};

union _STATE// Size=0x4 (Id=861)
{
    unsigned long StateAsUlong;// Offset=0x0 Size=0x4
    enum _GENERIC_STATE GenericState;// Offset=0x0 Size=0x4
    enum _ESM_STATE EsmState;// Offset=0x0 Size=0x4
};
