enum _WDF_STATE_NOTIFICATION_TYPE
{
    StateNotificationInvalid=0,
    StateNotificationEnterState=1,
    StateNotificationPostProcessState=2,
    StateNotificationLeaveState=4,
    StateNotificationAllStates=7
};

enum _WDF_DEVICE_POWER_POLICY_STATE
{
    WdfDevStatePwrPolInvalid=0,
    WdfDevStatePwrPolObjectCreated=1280,
    WdfDevStatePwrPolStarting=1281,
    WdfDevStatePwrPolStartingSucceeded=1282,
    WdfDevStatePwrPolStartingFailed=1283,
    WdfDevStatePwrPolStartingDecideS0Wake=1284,
    WdfDevStatePwrPolStartedIdleCapable=1285,
    WdfDevStatePwrPolTimerExpiredNoWake=1286,
    WdfDevStatePwrPolTimerExpiredNoWakeCompletePowerDown=1287,
    WdfDevStatePwrPolWaitingUnarmed=1288,
    WdfDevStatePwrPolWaitingUnarmedQueryIdle=1289,
    WdfDevStatePwrPolS0NoWakePowerUp=1290,
    WdfDevStatePwrPolS0NoWakeCompletePowerUp=1291,
    WdfDevStatePwrPolSystemSleepFromDeviceWaitingUnarmed=1292,
    WdfDevStatePwrPolSystemSleepNeedWake=1293,
    WdfDevStatePwrPolSystemSleepNeedWakeCompletePowerUp=1294,
    WdfDevStatePwrPolSystemSleepPowerRequestFailed=1295,
    WdfDevStatePwrPolCheckPowerPageable=1296,
    WdfDevStatePwrPolSleepingWakeWakeArrived=1297,
    WdfDevStatePwrPolSleepingWakeRevertArmWake=1298,
    WdfDevStatePwrPolSystemAsleepWakeArmed=1299,
    WdfDevStatePwrPolSystemWakeDeviceWakeEnabled=1300,
    WdfDevStatePwrPolSystemWakeDeviceWakeEnabledWakeCanceled=1301,
    WdfDevStatePwrPolSystemWakeDeviceWakeDisarm=1302,
    WdfDevStatePwrPolSystemWakeDeviceWakeTriggered=1303,
    WdfDevStatePwrPolSystemWakeDeviceWakeTriggeredS0=1304,
    WdfDevStatePwrPolSystemWakeDeviceWokeDisarm=1305,
    WdfDevStatePwrPolSleepingWakeWakeArrivedNP=34074,
    WdfDevStatePwrPolSleepingWakeRevertArmWakeNP=34075,
    WdfDevStatePwrPolSleepingWakePowerDownFailed=1308,
    WdfDevStatePwrPolSleepingWakePowerDownFailedWakeCanceled=1309,
    WdfDevStatePwrPolSystemAsleepWakeArmedNP=34078,
    WdfDevStatePwrPolSystemWakeDeviceWakeEnabledNP=34079,
    WdfDevStatePwrPolSystemWakeDeviceWakeEnabledWakeCanceledNP=34080,
    WdfDevStatePwrPolSystemWakeDeviceWakeDisarmNP=34081,
    WdfDevStatePwrPolSystemWakeDeviceWakeTriggeredNP=34082,
    WdfDevStatePwrPolSystemWakeDeviceWakeTriggeredS0NP=34083,
    WdfDevStatePwrPolSystemWakeDeviceWokeDisarmNP=34084,
    WdfDevStatePwrPolSystemWakeDeviceWakeCompletePowerUp=1317,
    WdfDevStatePwrPolSleeping=1318,
    WdfDevStatePwrPolSleepingNoWakePowerDown=1319,
    WdfDevStatePwrPolSleepingNoWakeCompletePowerDown=1320,
    WdfDevStatePwrPolSleepingNoWakeDxRequestFailed=1321,
    WdfDevStatePwrPolSleepingWakePowerDown=1322,
    WdfDevStatePwrPolSleepingSendWake=1323,
    WdfDevStatePwrPolSystemAsleepNoWake=1324,
    WdfDevStatePwrPolSystemWakeDeviceWakeDisabled=1325,
    WdfDevStatePwrPolSystemWakeDeviceToD0=1326,
    WdfDevStatePwrPolSystemWakeDeviceToD0CompletePowerUp=1327,
    WdfDevStatePwrPolSystemWakeQueryIdle=1328,
    WdfDevStatePwrPolStartedWakeCapable=1329,
    WdfDevStatePwrPolTimerExpiredDecideUsbSS=1330,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDown=1331,
    WdfDevStatePwrPolTimerExpiredWakeCapableSendWake=1332,
    WdfDevStatePwrPolTimerExpiredWakeCapableUsbSS=1333,
    WdfDevStatePwrPolTimerExpiredWakeCapableWakeArrived=1334,
    WdfDevStatePwrPolTimerExpiredWakeCapableCancelWake=1335,
    WdfDevStatePwrPolTimerExpiredWakeCapableWakeCanceled=1336,
    WdfDevStatePwrPolTimerExpiredWakeCapableCleanup=1337,
    WdfDevStatePwrPolTimerExpiredWakeCapableDxAllocFailed=1338,
    WdfDevStatePwrPolTimerExpiredWakeCompletedPowerDown=1339,
    WdfDevStatePwrPolTimerExpiredWakeCompletedPowerUp=1340,
    WdfDevStatePwrPolWaitingArmedUsbSS=1341,
    WdfDevStatePwrPolWaitingArmed=1342,
    WdfDevStatePwrPolWaitingArmedQueryIdle=1343,
    WdfDevStatePwrPolIoPresentArmed=1344,
    WdfDevStatePwrPolIoPresentArmedWakeCanceled=1345,
    WdfDevStatePwrPolS0WakeDisarm=1346,
    WdfDevStatePwrPolS0WakeCompletePowerUp=1347,
    WdfDevStatePwrPolTimerExpiredWakeSucceeded=1348,
    WdfDevStatePwrPolTimerExpiredWakeCompletedDisarm=1349,
    WdfDevStatePwrPolTimerExpiredWakeCapableWakeSucceeded=1350,
    WdfDevStatePwrPolTimerExpiredWakeCapableWakeFailed=1351,
    WdfDevStatePwrPolWakeFailedUsbSS=1352,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDownFailedCancelWake=1353,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDownFailedWakeCanceled=1354,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDownFailedUsbSS=1355,
    WdfDevStatePwrPolCancelingWakeForSystemSleep=1356,
    WdfDevStatePwrPolCancelingWakeForSystemSleepWakeCanceled=1357,
    WdfDevStatePwrPolDisarmingWakeForSystemSleepCompletePowerUp=1358,
    WdfDevStatePwrPolPowerUpForSystemSleepFailed=1359,
    WdfDevStatePwrPolWokeFromS0UsbSS=1360,
    WdfDevStatePwrPolWokeFromS0=1361,
    WdfDevStatePwrPolWokeFromS0NotifyDriver=1362,
    WdfDevStatePwrPolStoppingResetDevice=1363,
    WdfDevStatePwrPolStoppingResetDeviceCompletePowerUp=1364,
    WdfDevStatePwrPolStoppingResetDeviceFailed=1365,
    WdfDevStatePwrPolStoppingD0=1366,
    WdfDevStatePwrPolStoppingD0Failed=1367,
    WdfDevStatePwrPolStoppingDisarmWake=1368,
    WdfDevStatePwrPolStoppingDisarmWakeCancelWake=1369,
    WdfDevStatePwrPolStoppingDisarmWakeWakeCanceled=1370,
    WdfDevStatePwrPolStopping=1371,
    WdfDevStatePwrPolStoppingFailed=1372,
    WdfDevStatePwrPolStoppingSendStatus=1373,
    WdfDevStatePwrPolStoppingCancelTimer=1374,
    WdfDevStatePwrPolStoppingWaitForIdleTimeout=1375,
    WdfDevStatePwrPolStoppingCancelUsbSS=1376,
    WdfDevStatePwrPolStoppingWaitForUsbSSCompletion=1377,
    WdfDevStatePwrPolStoppingCancelWake=1378,
    WdfDevStatePwrPolStopped=1379,
    WdfDevStatePwrPolCancelUsbSS=1380,
    WdfDevStatePwrPolStarted=1381,
    WdfDevStatePwrPolStartedCancelTimer=1382,
    WdfDevStatePwrPolStartedWaitForIdleTimeout=1383,
    WdfDevStatePwrPolStartedWakeCapableCancelTimerForSleep=1384,
    WdfDevStatePwrPolStartedWakeCapableWaitForIdleTimeout=1385,
    WdfDevStatePwrPolStartedWakeCapableSleepingUsbSS=1386,
    WdfDevStatePwrPolStartedIdleCapableCancelTimerForSleep=1387,
    WdfDevStatePwrPolStartedIdleCapableWaitForIdleTimeout=1388,
    WdfDevStatePwrPolDeviceD0PowerRequestFailed=1389,
    WdfDevStatePwrPolDevicePowerRequestFailed=1390,
    WdfDevStatePwrPolGotoDx=1391,
    WdfDevStatePwrPolGotoDxInDx=1392,
    WdfDevStatePwrPolDx=1393,
    WdfDevStatePwrPolGotoD0=1394,
    WdfDevStatePwrPolGotoD0InD0=1395,
    WdfDevStatePwrPolFinal=1396,
    WdfDevStatePwrPolSleepingPowerDownNotProcessed=1397,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDownNotProcessed=1398,
    WdfDevStatePwrPolTimerExpiredNoWakePowerDownNotProcessed=1399,
    WdfDevStatePwrPolTimerExpiredNoWakePoweredDownDisableIdleTimer=1400,
    WdfDevStatePwrPolStoppingWaitingForImplicitPowerDown=1401,
    WdfDevStatePwrPolStoppingPoweringUp=1402,
    WdfDevStatePwrPolStoppingPoweringDown=1403,
    WdfDevStatePwrPolPowerUpForSystemSleepNotSeen=1404,
    WdfDevStatePwrPolWaitingArmedStoppingCancelUsbSS=1405,
    WdfDevStatePwrPolWaitingArmedWakeFailedCancelUsbSS=1406,
    WdfDevStatePwrPolWaitingArmedIoPresentCancelUsbSS=1407,
    WdfDevStatePwrPolWaitingArmedWakeSucceededCancelUsbSS=1408,
    WdfDevStatePwrPolCancelingUsbSSForSystemSleep=1409,
    WdfDevStatePwrPolStoppingD0CancelUsbSS=1410,
    WdfDevStatePwrPolStartingPoweredUp=1411,
    WdfDevStatePwrPolIdleCapableDeviceIdle=1412,
    WdfDevStatePwrPolDeviceIdleReturnToActive=1413,
    WdfDevStatePwrPolDeviceIdleSleeping=1414,
    WdfDevStatePwrPolDeviceIdleStopping=1415,
    WdfDevStatePwrPolTimerExpiredNoWakeUndoPowerDown=1416,
    WdfDevStatePwrPolWakeCapableDeviceIdle=1417,
    WdfDevStatePwrPolWakeCapableUsbSSCompleted=1418,
    WdfDevStatePwrPolTimerExpiredWakeCapableUndoPowerDown=1419,
    WdfDevStatePwrPolTimerExpiredWakeCompletedHardwareStarted=1420,
    WdfDevStatePwrPolStoppedRemoving=1421,
    WdfDevStatePwrPolRemoved=1422,
    WdfDevStatePwrPolRestarting=1423,
    WdfDevStatePwrPolRestartingFailed=1424,
    WdfDevStatePwrPolStartingPoweredUpFailed=1425,
    WdfDevStatePwrPolTimerExpiredNoWakeReturnToActive=1426,
    WdfDevStatePwrPolWaitingArmedWakeInterruptFired=1427,
    WdfDevStatePwrPolSystemWakeDeviceWakeInterruptFired=1428,
    WdfDevStatePwrPolSystemWakeDeviceWakeInterruptFiredNP=34197,
    WdfDevStatePwrPolTimerExpiredWakeCapableWakeInterruptArrived=1430,
    WdfDevStatePwrPolTimerExpiredWakeCapablePowerDownFailedWakeInterruptArrived=1431,
    WdfDevStatePwrPolWaitingArmedWakeInterruptFiredDuringPowerDown=1432,
    WdfDevStatePwrPolNull=1433
};

struct _unnamed_424// Size=0x8 (Id=424)
{
    enum _WDF_DEVICE_POWER_POLICY_STATE CurrentState;// Offset=0x0 Size=0x4
    enum _WDF_DEVICE_POWER_POLICY_STATE NewState;// Offset=0x4 Size=0x4
};

struct _unnamed_425// Size=0x4 (Id=425)
{
    enum _WDF_DEVICE_POWER_POLICY_STATE CurrentState;// Offset=0x0 Size=0x4
};

union _unnamed_426// Size=0x8 (Id=426)
{
    struct _unnamed_424 EnterState;// Offset=0x0 Size=0x8
    struct _unnamed_425 PostProcessState;// Offset=0x0 Size=0x4
    struct _unnamed_424 LeaveState;// Offset=0x0 Size=0x8
};

struct _WDF_DEVICE_POWER_POLICY_NOTIFICATION_DATA// Size=0xc (Id=243)
{
    enum _WDF_STATE_NOTIFICATION_TYPE Type;// Offset=0x0 Size=0x4
    union _unnamed_426 Data;// Offset=0x4 Size=0x8
};
