enum _SleepstudyHelper_Namespace
{
    SSH_PDO=0,
    SSH_SLEEPSTUDY_HANDLE=1,
    SSH_FDO=2,
    SSH_PID=3,
    SSH_GENERAL_HANDLE=4,
    SSH_CONNECTION_DEVICE=5,
    SSH_CONNECTION_OPREGION=6,
    SSH_NONE=7
};
