enum _WDF_REQUEST_SEND_OPTIONS_FLAGS
{
    WDF_REQUEST_SEND_OPTION_TIMEOUT=1,
    WDF_REQUEST_SEND_OPTION_SYNCHRONOUS=2,
    WDF_REQUEST_SEND_OPTION_IGNORE_TARGET_STATE=4,
    WDF_REQUEST_SEND_OPTION_SEND_AND_FORGET=8,
    WDF_REQUEST_SEND_OPTION_IMPERSONATE_CLIENT=65536,
    WDF_REQUEST_SEND_OPTION_IMPERSONATION_IGNORE_FAILURE=131072
};
