struct _USBHUB3_TRIAGE_INFO// Size=0x178 (Id=492)
{
    unsigned long Version;// Offset=0x0 Size=0x4
    unsigned long ConfigurationDescriptorOffset;// Offset=0x4 Size=0x4
    unsigned long HubControlRequestWdfRequestOffset;// Offset=0x8 Size=0x4
    unsigned long ControlRequestIrpOffset;// Offset=0xc Size=0x4
    unsigned long HubFdoDeviceOffset;// Offset=0x10 Size=0x4
    unsigned long ControlWdfRequestOffset;// Offset=0x14 Size=0x4
    unsigned long StatusChangeInterruptWdfRequestOffset;// Offset=0x18 Size=0x4
    unsigned long HubContextSize;// Offset=0x1c Size=0x4
    unsigned long ConfigurationDescriptorSize;// Offset=0x20 Size=0x4
    unsigned long HubControlRequestSize;// Offset=0x24 Size=0x4
    unsigned long RootHub30PortInfoArrayOffset;// Offset=0x28 Size=0x4
    unsigned long RootHub30PortInfoCountOffset;// Offset=0x2c Size=0x4
    unsigned long RootHub30PortInfoCountSize;// Offset=0x30 Size=0x4
    unsigned long RootHub30PortInfoSize;// Offset=0x34 Size=0x4
    unsigned long RootHub20PortInfoArrayOffset;// Offset=0x38 Size=0x4
    unsigned long RootHub20PortInfoCountOffset;// Offset=0x3c Size=0x4
    unsigned long RootHub20PortInfoCountSize;// Offset=0x40 Size=0x4
    unsigned long RootHub20PortInfoSize;// Offset=0x44 Size=0x4
    unsigned long PSMListHeadOffset;// Offset=0x48 Size=0x4
    unsigned long PortContextSize;// Offset=0x4c Size=0x4
    unsigned long PortContextOffset;// Offset=0x50 Size=0x4
    unsigned long PortContextIfrLogOffset;// Offset=0x54 Size=0x4
    unsigned long DSMListHeadOffset;// Offset=0x58 Size=0x4
    unsigned long DeviceContextOffset;// Offset=0x5c Size=0x4
    unsigned long DevicePdoContextOffset;// Offset=0x60 Size=0x4
    unsigned long DeviceCurrentConfigurationOffset;// Offset=0x64 Size=0x4
    unsigned long DeviceOldDeviceConfigurationOffset;// Offset=0x68 Size=0x4
    unsigned long DeviceNextInterfaceToSetOffset;// Offset=0x6c Size=0x4
    unsigned long DeviceOldInterfaceOffset;// Offset=0x70 Size=0x4
    unsigned long DeviceNewInterfaceOffset;// Offset=0x74 Size=0x4
    unsigned long DeviceEndPointsToBeEnabledOffset;// Offset=0x78 Size=0x4
    unsigned long DeviceEndPointsToBeDisabledOffset;// Offset=0x7c Size=0x4
    unsigned long DeviceEndPointsToRemainUnchangedOffset;// Offset=0x80 Size=0x4
    unsigned long DeviceUcxEndPointArrayCountOffset;// Offset=0x84 Size=0x4
    unsigned long DeviceControlRequestOffset;// Offset=0x88 Size=0x4
    unsigned long DeviceWdfUcxRequestOffset;// Offset=0x8c Size=0x4
    unsigned long DeviceUcxRequestIrpOffset;// Offset=0x90 Size=0x4
    unsigned long DeviceWdfUcxIoctlRequestMemoryOffset;// Offset=0x94 Size=0x4
    unsigned long DeviceWdfCurrentClientRequestOffset;// Offset=0x98 Size=0x4
    unsigned long DeviceWdfDeviceInitOffset;// Offset=0x9c Size=0x4
    unsigned long DeviceCurrentTargetPipeOffset;// Offset=0xa0 Size=0x4
    unsigned long DeviceDescriptorOffset;// Offset=0xa4 Size=0x4
    unsigned long DeviceCompatIdInterfaceDescriptorOffset;// Offset=0xa8 Size=0x4
    unsigned long DeviceConfigurationDescriptorOffset;// Offset=0xac Size=0x4
    unsigned long DeviceLanguageIdDescriptorOffset;// Offset=0xb0 Size=0x4
    unsigned long DeviceProductIdStringDescriptorOffset;// Offset=0xb4 Size=0x4
    unsigned long DeviceDeviceQualifierDescriptorOffset;// Offset=0xb8 Size=0x4
    unsigned long DeviceBOSDescriptorOffset;// Offset=0xbc Size=0x4
    unsigned long DeviceMsExtConfigDescOffset;// Offset=0xc0 Size=0x4
    unsigned long DeviceMsExtPropertyDescOffset;// Offset=0xc4 Size=0x4
    unsigned long DevicePdoAssociatedContextOffset;// Offset=0xc8 Size=0x4
    unsigned long DevicePdoIdleIrpOffset;// Offset=0xcc Size=0x4
    unsigned long DevicePdoWakeNotificationOffset;// Offset=0xd0 Size=0x4
    unsigned long DeviceContextSize;// Offset=0xd4 Size=0x4
    unsigned long DevicePdoContextSize;// Offset=0xd8 Size=0x4
    unsigned long DeviceEndPointSizeOfCountFieldOffset;// Offset=0xdc Size=0x4
    unsigned long DeviceControlRequestSize;// Offset=0xe0 Size=0x4
    unsigned long IrpSize;// Offset=0xe4 Size=0x4
    unsigned long PipeHandleSize;// Offset=0xe8 Size=0x4
    unsigned long UsbInterfaceDescriptorSize;// Offset=0xec Size=0x4
    unsigned long UsbStringDescriptorSize;// Offset=0xf0 Size=0x4
    unsigned long UsbDeviceQualifierDescriptorSize;// Offset=0xf4 Size=0x4
    unsigned long BOSDescriptorSize;// Offset=0xf8 Size=0x4
    unsigned long MsExtConfigDescSize;// Offset=0xfc Size=0x4
    unsigned long MsExtPropDescSize;// Offset=0x100 Size=0x4
    unsigned long DeviceConfigurationSize;// Offset=0x104 Size=0x4
    unsigned long UsbEndpointDescriptorSize;// Offset=0x108 Size=0x4
    unsigned long DeviceUsbConfigurationDescriptorSize;// Offset=0x10c Size=0x4
    unsigned long ConInterfaceListOffset;// Offset=0x110 Size=0x4
    unsigned long ConDeviceConfigurationDescriptorOffset;// Offset=0x114 Size=0x4
    unsigned long InterfaceHandleSize;// Offset=0x118 Size=0x4
    unsigned long DeviceConfigurationInterfaceListOffset;// Offset=0x11c Size=0x4
    unsigned long IfHNumOfEndpointsOffset;// Offset=0x120 Size=0x4
    unsigned long IfHPipeHandleOffset;// Offset=0x124 Size=0x4
    unsigned long IfHNumOfEndpointsSize;// Offset=0x128 Size=0x4
    unsigned long IfHInterfaceLinkOffset;// Offset=0x12c Size=0x4
    unsigned long IfHInterfaceDescriptorOffset;// Offset=0x130 Size=0x4
    unsigned long PiHEndpointDescriptorOffset;// Offset=0x134 Size=0x4
    unsigned long PipeHandleUcxEndpointOffset;// Offset=0x138 Size=0x4
    unsigned long IfrLogHeaderOffset;// Offset=0x13c Size=0x4
    unsigned long IfrLogHeaderSize;// Offset=0x140 Size=0x4
    unsigned long IfrLogSizeOffset;// Offset=0x144 Size=0x4
    unsigned long IfrSizeOfLogSizeField;// Offset=0x148 Size=0x4
    unsigned long IfrDriverContextOffset;// Offset=0x14c Size=0x4
    unsigned long IfrDriverContextSize;// Offset=0x150 Size=0x4
    void * GlobalDriverObjectPtr;// Offset=0x158 Size=0x8
    void * WppGlobalControlPtr;// Offset=0x160 Size=0x8
    unsigned long WppGlobalControlSize;// Offset=0x168 Size=0x4
    void * WdfTriageInfoPtr;// Offset=0x170 Size=0x8
};
