enum _HUB_WAKE_STATE
{
    HUB_WAKESTATE_UNINITIALIZED=0,
    HUB_WAKESTATE_DISARMED=1,
    HUB_WAKESTATE_WAITING=2,
    HUB_WAKESTATE_WAITING_CANCELLED=3,
    HUB_WAKESTATE_ARMED=4,
    HUB_WAKESTATE_ARMING_CANCELLED=5,
    HUB_WAKESTATE_COMPLETING=7
};
