enum MFND_ADMIN_COMMAND_IDENTIFIERS
{
    MFND_ADMIN_COMMAND_ID_IDENTIFY_MFND=1,
    MFND_ADMIN_COMMAND_ID_IDENTIFY_CHILD_CONTROLLER=2,
    MFND_ADMIN_COMMAND_ID_MANAGEMENT=3,
    MFND_ADMIN_COMMAND_ID_CC_CONTROL=4,
    MFND_ADMIN_COMMAND_ID_GET_CC_LOG_PAGE=5,
    MFND_ADMIN_COMMAND_ID_GET_CC_COMMAND_PERMISSION=6,
    MFND_ADMIN_COMMAND_ID_SET_CC_COMMAND_PERMISSION=7
};
