enum _DXGK_DIAG_TYPE
{
    DXGK_DIAG_TYPE_NONE=0,
    DXGK_DIAG_TYPE_SDC=1,
    DXGK_DIAG_TYPE_HPD=2,
    DXGK_DIAG_TYPE_DC_ORIGIN=3,
    DXGK_DIAG_TYPE_USER_CDS=4,
    DXGK_DIAG_TYPE_DRV_CDS=5,
    DXGK_DIAG_TYPE_CODE_POINT=6,
    DXGK_DIAG_TYPE_QDC=7,
    DXGK_DIAG_TYPE_MONITOR_MGR=8,
    DXGK_DIAG_TYPE_CONNECTEDSET_NOT_FOUND=9,
    DXGK_DIAG_TYPE_DISPDIAG_COLLECTED=10,
    DXGK_DIAG_TYPE_BML_PACKET=11,
    DXGK_DIAG_TYPE_BML_PACKET2=12,
    DXGK_DIAG_TYPE_COMMIT_VIDPN_FAILED=13,
    DXGK_DIAG_TYPE_DRIVER_RECOMMEND_VIDPN=14,
    DXGK_DIAG_TYPE_OUTPUTDUPL=15,
    DXGK_DIAG_TYPE_MONITOR_BRIGHTNESS=16,
    DXGK_DIAG_TYPE_CCD_DATABASE_ACCESS=17,
    DXGK_DIAG_TYPE_MIRACAST_SESSION_START_DONE=18,
    DXGK_DIAG_TYPE_MIRACAST_SESSION_START=19,
    DXGK_DIAG_TYPE_MIRACAST_SESSION_START_DONE_EX=20,
    DXGK_DIAG_TYPE_SDC2=21,
    DXGK_DIAG_TYPE_QDC2=22,
    DXGK_DIAG_TYPE_FUNCTIONALIZE_PACKET=23,
    DXGK_DIAG_TYPE_MIRACAST_SESSION_START_DONE_EX2=24,
    DXGK_DIAG_TYPE_MONITOR_BRIGHTNESS_EX=25,
    DXGK_DIAG_TYPE_ADAPTER_START=26,
    DXGK_DIAG_TYPE_PADDING=27,
    DXGK_DIAG_TYPE_PERSISTENT_DUP=28,
    DXGK_DIAG_TYPE_MESSAGE=29,
    DXGK_DIAG_TYPE_CODE_POINT_ADAPTERLUID=30,
    DXGK_DIAG_TYPE_FUNCTIONALIZE_PACKET2=31,
    DXGK_DIAG_TYPE_BML_PACKET3=32,
    DXGK_DIAG_TYPE_COMMIT_VIDPN_FAILED2=33,
    DXGK_DIAG_TYPE_DRIVER_RECOMMEND_VIDPN2=34,
    DXGK_DIAG_TYPE_CCD_DATABASE_ACCESS2=35,
    DXGK_DIAG_TYPE_FUNCTIONALIZE_PACKET3=36,
    DXGK_DIAG_TYPE_COMMIT_VIDPN_FAILED3=37,
    DXGK_DIAG_TYPE_SDC3=38,
    DXGK_DIAG_TYPE_QDC3=39,
    DXGK_DIAG_TYPE_MONITOR_BRIGHTNESS3=40,
    DXGK_DIAG_TYPE_ADAPTER_START2=41,
    DXGK_DIAG_TYPE_MAX=41,
    DXGK_DIAG_TYPE_FORCE_UINT32=-1
};

struct _DXGK_DIAG_HEADER// Size=0x30 (Id=189)
{
    enum _DXGK_DIAG_TYPE Type;// Offset=0x0 Size=0x4
    unsigned int Size;// Offset=0x4 Size=0x4
    unsigned long long LogTimestamp;// Offset=0x8 Size=0x8
    unsigned char ProcessName[16];// Offset=0x10 Size=0x10
    unsigned long long ThreadId;// Offset=0x20 Size=0x8
    unsigned int Index;// Offset=0x28 Size=0x4
    unsigned int WdLogIdx;// Offset=0x2c Size=0x4
};
