enum _D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL
{
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_NO_CHANGE=0,
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_ENABLE=1,
    D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL_BYPASS=2
};

struct _D3DKMDT_COLORSPACE_TRANSFORM_MATRIX_V2// Size=0x18030 (Id=617)
{
    enum _D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL StageControlLookupTable1DDegamma;// Offset=0x0 Size=0x4
    struct D3DDDI_DXGI_RGB LookupTable1DDegamma[4096];// Offset=0x4 Size=0xc000
    enum _D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL StageControlColorMatrix3x3;// Offset=0xc004 Size=0x4
    float ColorMatrix3x3[3][3];// Offset=0xc008 Size=0x24
    enum _D3DKMDT_COLORSPACE_TRANSFORM_STAGE_CONTROL StageControlLookupTable1DRegamma;// Offset=0xc02c Size=0x4
    struct D3DDDI_DXGI_RGB LookupTable1DRegamma[4096];// Offset=0xc030 Size=0xc000
};
