enum _STORAGE_MINIPORT_ERROR_REASON_CODE
{
    MINIPORT_ERROR_SRB_NOT_COMPLETED_ON_RESET=1,
    MINIPORT_ERROR_SRB_NOT_COMPLETED_ON_ABORT=2,
    MINIPORT_ERROR_SRB_TIMEOUT=3,
    MINIPORT_ERROR_CRYPTO_FAILED=4,
    MINIPORT_ERROR_COMPLETE_SRB_AT_DIRQL=5,
    MINIPORT_ERROR_STORMQ_PROPERTY_FAILURE=6,
    MINIPORT_ERROR_UNEXPECTED_NULL_SRB=7
};
