enum MFND_VENDOR_SPECIFIC_STATUS_CODES
{
    MFND_STATUS_INVALID_MCID=192,
    MFND_STATUS_INVALID_CCID=193,
    MFND_STATUS_INSUFFICIENT_BUFFER=194,
    MFND_STATUS_INSUFFICIENT_CHILD_CONTROLLER=195,
    MFND_STATUS_INSUFFICIENT_RESOURCE=196,
    MFND_STATUS_POWER_CYCLE_NEEDED=197,
    MFND_STATUS_NSSR_NEEDED=198,
    MFND_STATUS_FLR_NEEDED=199,
    MFND_STATUS_PCIE_PERST_RESET_NEEDED=200,
    MFND_STATUS_INVALID_PRIVILEGE_MODE=201,
    MFND_STATUS_ADMIN_COMMAND_PERMISSION_FAILURE=202
};
