enum MFND_ADMIN_COMMANDS
{
    NVME_ADMIN_COMMAND_MFND_NODATA=208,
    NVME_ADMIN_COMMAND_MFND_HOST_TO_CONTROLLER=209,
    NVME_ADMIN_COMMAND_MFND_CONTROLLER_TO_HOST=210,
    NVME_ADMIN_COMMAND_MFND_BIDIRECTION=211
};
