enum NVME_VENDOR_LOG_PAGES
{
    NVME_LOG_PAGE_OCP_DEVICE_SMART_INFORMATION=192,
    NVME_LOG_PAGE_OCP_DEVICE_ERROR_RECOVERY=193,
    NVME_LOG_PAGE_OCP_FIRMWARE_ACTIVATION_HISTORY=194,
    NVME_LOG_PAGE_OCP_LATENCY_MONITOR=195,
    NVME_LOG_PAGE_OCP_DEVICE_CAPABILITIES=196,
    NVME_LOG_PAGE_OCP_UNSUPPORTED_REQUIREMENTS=197,
    NVME_LOG_PAGE_OCP_TCG_CONFIGURATION=200,
    NVME_LOG_PAGE_OCP_TCG_HISTORY=201
};
