enum NVME_RESERVATION_TYPES
{
    NVME_RESERVATION_TYPE_RESERVED=0,
    NVME_RESERVATION_TYPE_WRITE_EXCLUSIVE=1,
    NVME_RESERVATION_TYPE_EXCLUSIVE_ACCESS=2,
    NVME_RESERVATION_TYPE_WRITE_EXCLUSIVE_REGISTRANTS_ONLY=3,
    NVME_RESERVATION_TYPE_EXCLUSIVE_ACCESS_REGISTRANTS_ONLY=4,
    NVME_RESERVATION_TYPE_WRITE_EXCLUSIVE_ALL_REGISTRANTS=5,
    NVME_RESERVATION_TYPE_EXCLUSIVE_ACCESS_ALL_REGISTRANTS=6
};
