enum NVME_RESERVATION_REGISTER_PTPL_STATE_CHANGES
{
    NVME_RESERVATION_REGISTER_PTPL_STATE_NO_CHANGE=0,
    NVME_RESERVATION_REGISTER_PTPL_STATE_RESERVED=1,
    NVME_RESERVATION_REGISTER_PTPL_STATE_SET_TO_0=2,
    NVME_RESERVATION_REGISTER_PTPL_STATE_SET_TO_1=3
};
