enum NVME_ACCESS_FREQUENCIES
{
    NVME_ACCESS_FREQUENCY_NONE=0,
    NVME_ACCESS_FREQUENCY_TYPICAL=1,
    NVME_ACCESS_FREQUENCY_INFR_WRITE_INFR_READ=2,
    NVME_ACCESS_FREQUENCY_INFR_WRITE_FR_READ=3,
    NVME_ACCESS_FREQUENCY_FR_WRITE_INFR_READ=4,
    NVME_ACCESS_FREQUENCY_FR_WRITE_FR_READ=5,
    NVME_ACCESS_FREQUENCY_ONE_TIME_READ=6,
    NVME_ACCESS_FREQUENCY_SPECULATIVE_READ=7,
    NVME_ACCESS_FREQUENCY_WILL_BE_OVERWRITTEN=8
};
