enum NVME_STATUS_TYPES
{
    NVME_STATUS_TYPE_GENERIC_COMMAND=0,
    NVME_STATUS_TYPE_COMMAND_SPECIFIC=1,
    NVME_STATUS_TYPE_MEDIA_ERROR=2,
    NVME_STATUS_TYPE_PATH_RELATED=3,
    NVME_STATUS_TYPE_VENDOR_SPECIFIC=7
};
