enum FxRequestContextTypes
{
    FX_REQUEST_CONTEXT_TYPE_NONE=0,
    FX_RCT_IO=1,
    FX_RCT_INTERNAL_IOCTL_OTHERS=2,
    FX_RCT_USB_PIPE_XFER=16,
    FX_RCT_USB_URB_REQUEST=17,
    FX_RCT_USB_PIPE_REQUEST=18,
    FX_RCT_USB_CONTROL_REQUEST=19,
    FX_RCT_USB_STRING_REQUEST=20
};
