enum _WDF_REQUEST_FATAL_ERROR_CODES
{
    WDF_REQUEST_FATAL_ERROR_NO_MORE_STACK_LOCATIONS=1,
    WDF_REQUEST_FATAL_ERROR_NULL_IRP=2,
    WDF_REQUEST_FATAL_ERROR_REQUEST_ALREADY_SENT=3,
    WDF_REQUEST_FATAL_ERROR_INFORMATION_LENGTH_MISMATCH=4,
    WDF_REQUEST_FATAL_ERROR_REQUEST_NOT_IN_QUEUE=5
};
