enum _SOC_SUBSYSTEM_TYPE
{
    SOC_SUBSYS_WIRELESS_MODEM=0,
    SOC_SUBSYS_AUDIO_DSP=1,
    SOC_SUBSYS_WIRELSS_CONNECTIVITY=2,
    SOC_SUBSYS_SENSORS=3,
    SOC_SUBSYS_COMPUTE_DSP=4,
    SOC_SUBSYS_SECURE_PROC=5,
    SOC_SUBSYS_VENDOR_DEFINED=65536
};
