enum _WDF_DISPATCH_IRP_TO_IO_QUEUE_FLAGS
{
    WDF_DISPATCH_IRP_TO_IO_QUEUE_NO_FLAGS=0,
    WDF_DISPATCH_IRP_TO_IO_QUEUE_INVOKE_INCALLERCTX_CALLBACK=1,
    WDF_DISPATCH_IRP_TO_IO_QUEUE_PREPROCESSED_IRP=2
};
