enum FX_VALIDATE_FUNCTIONS_FLAGS
{
    FX_VALIDATE_OPTION_NONE_SPECIFIED=0,
    FX_VALIDATE_OPTION_PARENT_NOT_ALLOWED=1,
    FX_VALIDATE_OPTION_EXECUTION_LEVEL_ALLOWED=2,
    FX_VALIDATE_OPTION_SYNCHRONIZATION_SCOPE_ALLOWED=4,
    FX_VALIDATE_OPTION_ATTRIBUTES_REQUIRED=8,
    FX_VALIDATE_OPTION_PARENT_REQUIRED_FLAG=16,
    FX_VALIDATE_OPTION_PARENT_REQUIRED=24
};
