enum _NT_IORING_CREATE_REQUIRED_FLAGS
{
    NT_IORING_CREATE_REQUIRED_FLAG_NONE=0
};

enum _NT_IORING_CREATE_ADVISORY_FLAGS
{
    NT_IORING_CREATE_ADVISORY_FLAG_NONE=0,
    NT_IORING_CREATE_SKIP_BUILDER_PARAM_CHECKS=1
};

struct _NT_IORING_CREATE_FLAGS// Size=0x8 (Id=2143)
{
    enum _NT_IORING_CREATE_REQUIRED_FLAGS Required;// Offset=0x0 Size=0x4
    enum _NT_IORING_CREATE_ADVISORY_FLAGS Advisory;// Offset=0x4 Size=0x4
};
