enum _OPLOCK_TELEMETRY_FLAGS
{
    OPLOCK_TELEMETRY_FLAG_NONE=0,
    OPLOCK_TELEMETRY_FLAG_INTEGRITY_UNKNOWN=1,
    OPLOCK_TELEMETRY_FLAG_REMOTE_ORIGIN=2,
    OPLOCK_TELEMETRY_FLAG_HAS_RESTORE_PRIVILEGE=4,
    OPLOCK_TELEMETRY_FLAG_DATA_COLLECTED=-2147483648
};
