enum _NT_IORING_OP_FLAGS
{
    NT_IORING_OP_FLAG_NONE=0,
    NT_IORING_OP_FLAG_REGISTERED_FILE_0=1,
    NT_IORING_OP_FLAG_REGISTERED_FILE=1,
    NT_IORING_OP_FLAG_REGISTERED_BUFFER_0=2,
    NT_IORING_OP_FLAG_REGISTERED_BUFFER=2
};

enum _NT_IORING_REG_BUFFERS_REQ_FLAGS
{
    NT_IORING_REG_BUFFERS_REQ_FLAG_NONE=0
};

enum _NT_IORING_REG_BUFFERS_ADV_FLAGS
{
    NT_IORING_REG_BUFFERS_ADV_FLAG_NONE=0
};

struct _NT_IORING_REG_BUFFERS_FLAGS// Size=0x8 (Id=2274)
{
    enum _NT_IORING_REG_BUFFERS_REQ_FLAGS Required;// Offset=0x0 Size=0x4
    enum _NT_IORING_REG_BUFFERS_ADV_FLAGS Advisory;// Offset=0x4 Size=0x4
};

struct _NT_IORING_OP_REGISTER_BUFFERS// Size=0x18 (Id=2205)
{
    enum _NT_IORING_OP_FLAGS CommonOpFlags;// Offset=0x0 Size=0x4
    struct _NT_IORING_REG_BUFFERS_FLAGS Flags;// Offset=0x4 Size=0x8
    unsigned int Count;// Offset=0xc Size=0x4
    struct IORING_BUFFER_INFO * Buffers;// Offset=0x10 Size=0x8
};
