struct KDeletePtr<_NDIS_MINIPORT_DRIVER_CHARACTERISTICS>// Size=0x1 (Id=438)
{
    void KDeletePtr<_NDIS_MINIPORT_DRIVER_CHARACTERISTICS>();
    void operator()(struct _NDIS_MINIPORT_DRIVER_CHARACTERISTICS * );
};
