enum FxDevicePwrRequirementStates
{
    DprInvalid=0,
    DprUnregistered=1,
    DprDevicePowerRequiredD0=2,
    DprDevicePowerNotRequiredD0=3,
    DprDevicePowerNotRequiredDx=4,
    DprDevicePowerRequiredDx=5,
    DprReportingDevicePowerAvailable=6,
    DprWaitingForDevicePowerRequiredD0=7,
    DprDirectedPowerDownInitiate=8,
    DprDirectedPowerDownComplete=9,
    DprDirectedPowerUpInitiate=10,
    DprDirectedPowerUpComplete=11,
    DprDirectedPowerDownFailedWaitingForUp=12,
    DprDirectedPowerDownFailedUpArrived=13,
    DprDirectedPowerUpFailedComplete=14,
    DprMax=15
};
